import Head from 'next/head'
import { useQuery } from 'urql'
import { PRODUCT_QUERY } from '../lib/query'
import Product from '../components/Product'
import { Gallery } from '../styles/Gallery'

export default function Home() {
  //FETCH PRODUCTS FROM STRAPI
  const [results] = useQuery({ query: PRODUCT_QUERY })
  const { data, fetching, error } = results

  // CHECK FOR DATA COMING IN 
  if (fetching) return <p>Loading...</p>
  if (error) return <p>porcaccio di..! {error.message}</p>
  const products = data.products.data

  console.log(products);
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Gallery>
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </main>


    </div>
  )
}
